### ISSUE TITLE
Uninstalling collections

### ISSUE THREAD

**Issue by sgtlighttree** [Kumar-Saksham/CSMM-CLI#2]
I have installed some large collections and it would be a hassle uninstalling each and every item in the collection manually. I tried using the `uninstall` command on a collection but is just says `Error Uninstalling: Item with given id is not installed`, even when the collection itself is now installed. 

Would it be possible to implement a way to uninstall collections? Thanks!

**Comment by Kumar-Saksham** [comment]
Collections themselves are not installed. When you install a collection it just installs each and very individual item on the list, so the error `Error Uninstalling: Item with given id is not installed` is the intended response, since collection's id does not match any mod's id. Adding this feature will add extra overhead to the `uninstall` command since it will have to ping steam workshop for every uninstall command that is executed. Currently there is no plan on adding such feature.

You can uninstall multiple items by just using the `csmm uninstall` command without any ids, it will present a multiselect list where you can select multiple items by pressing the `SPACE` key and  finally pressing the enter key. It will uninstall all selected items at once.
